[project]
name = "hw1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Edvin Sundström", email = "edvin.suundstrom@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
hw1 = "hw1:main"

[tool.ruff]
line-length = 88

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
